// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 28 Aug 2018 20:17:56 PDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package thinger

/*
#cgo pkg-config: libconfuse sdl2
#include "thinger.h"
#include <stdlib.h>
*/
import "C"

func ExThinger() (int, error) {
	
	rc, err := C.thinger()
	if err != nil {
		panic(err)
	}
	
	return int(rc), nil
}
